version: '3.8'

services:

  redis:
    image: redis:7
    container_name: saraldb-redis
    ports:
        - "6380:6379"

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    container_name: saraldb-api
    ports:
          - "5001:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    container_name: saraldb-web
    ports:
    - "3001:3000"
    depends_on:
      - api